### ISSUE TITLE
Nim 0.13.1?

### ISSUE THREAD

**Issue by bhtek** [tulayang/asyncdocker#1]
Where to find that release? Isn't the latest at this date 0.13.0?

**Comment by tulayang** [comment]
@bhtek

0.13.0 should be able to work properly. This is my carelessness.

In addition, you can get 0.13.1 (devel branch) like this:

``` sh
git clone -b devel git://github.com/nim-lang/Nim.git
cd Nim
git clone -b devel --depth 1 git://github.com/nim-lang/csources
cd csources && sh build.sh
cd ..
bin/nim c koch
./koch boot -d:release
```

Repeat again: 0.13.0 should be able to work properly.

**Comment by bhtek** [comment]
Works now, thanks!
